---
title: "studie2"
author: "flooo2"
date: "2023-07-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
data <- read.csv("results-survey768925juli13.csv")
data <- data[!is.na(data$Bf.b1.), ]
```
```{r}
#allgemeine fragen
N <- nrow(data)
M_alter <- mean(data$Of1)
Mdn_alter <- median(data$Of1)
SD_alter <- sd(data$Of1)
n_w <- sum(data$Of2 == "w")
n_m <- sum(data$Of2 == "m")
#mir egal, ob wir generell zwischen geschlechtern unterscheiden wollen; wollte nur schauen, wie das geht; wahrscheinlich nur bei vielen teilnehmern?
M_w_b_nutzung <- mean(data$Of3[data$Of2 == "w"])
M_m_b_nutzung <- mean(data$Of3[data$Of2 == "m"])
M_b_nutzung <- mean(data$Of3)
median_bereal <- median(data$Of3)
median_instagram <- median(data$Of4)
SD_b_nutzung <- sd(data$Of3)
M_w_i_nutzung <- mean(data$Of4[data$Of2 == "w"])
M_m_i_nutzung <- mean(data$Of4[data$Of2 == "m"])
M_i_nutzung <- mean(data$Of4)
SD_i_nutzung <- sd(data$Of4)
privat <- sum(data$Of5 == "p")
oeffentlich <-sum(data$Of5 == "o")
```

```{r}
#b = bereal, i = instagram, s = social media
data_b <- data[, grepl("^Bf", names(data))]
data_i <- data[, grepl("^If", names(data))]
data_s <- data[, grepl("^Af", names(data))]
data_bis <- cbind(data_b, data_i, data_s)

#sollten wir anscheinend gar nicht tun
M_bis <- colMeans(data_bis, na.rm = TRUE)
Mdn_bis <- apply(data_bis, 2, median, na.rm = TRUE)
SD_bis <- apply(data_bis, 2, sd, na.rm = TRUE)
M_Mdn_SD <- data.frame(M = M_bis,
                           Mdn = Mdn_bis,
                           SD = SD_bis)
```

```{r}
#das sollten wir tun, weiß aber nicht, ob das bei b und i sinn macht, die skala haben wir uns ja selber ausgedacht...
data_b$M <- rowMeans(data_b)
data_i$M <- rowMeans(data_i)
data_s$M <- rowMeans(data_s)

#mourad
t_bi <- t.test(data_b$M, data_i$M) #5
t_bi_a <- t_bi$parameter 
t_bi_s <- t_bi$statistic
t_bi_p <- t_bi$p.value 
#eig sind die unteren 3 zeilen unnötig, man kann im environment auf t_bi klicken; war in der übung auch so, die werte sind wahrscheinlich wichtig


c_bs <- cor.test(data_b$M, data_s$M) #6.1
c_bs_a <- c_bs$parameter
c_bs_e <- c_bs$estimate
c_bs_p <- c_bs$p.value

c_is <- cor.test(data_i$M, data_s$M) #6.2
c_is_a <- c_is$parameter
c_is_e <- c_is$estimate
c_is_p <- c_is$p.value

M_bi = (data_b$M + data_i$M) / 2 #6.3
c_bis <- cor.test(M_bi, data_s$M) 
c_bis_a <- c_bis$parameter
c_bis_e <- c_bis$estimate
c_bis_p <- c_bis$p.value


c_ib <- cor.test(data_i$M, data_b$M) #i und b
c_ib_a <- c_ib$parameter
c_ib_e <- c_ib$estimate
c_ib_p <- c_ib$p.value
```

```{r}
#voraussetzungen für die tests von eben
#normalverteilt
qqnorm(rowMeans(data_b))
qqline(rowMeans(data_b))
mtext("BeReal", side = 3, line = 3, cex = 1.2)

qqnorm(rowMeans(data_i))
qqline(rowMeans(data_i))
mtext("Instagram", side = 3, line = 3, cex = 1.2)

qqnorm(rowMeans(data_s))
qqline(rowMeans(data_s))
mtext("ASMC", side = 3, line = 3, cex = 1.2)


#linearer zusammenhang
plot(data_b$M, data_i$M, 
     main = "Scatter Plot", 
     xlab = "BeReal", 
     ylab = "Instagram")
mtext("BeReal und Instagram", side = 3, line = 3, cex = 1.2)

plot(data_b$M, data_s$M, 
     main = "Scatter Plot", 
     xlab = "BeReal", 
     ylab = "ASMC")
mtext("BeReal und ASMC", side = 3, line = 3, cex = 1.2)

plot(data_i$M, data_s$M, 
     main = "Scatter Plot", 
     xlab = "Instagram", 
     ylab = "ASMC")
mtext("Instagram und ASMC", side = 3, line = 3, cex = 1.2)


#keine ausreißer
means_b <- data.frame(M = rowMeans(data_b))
model <- lm(M ~ 1, data = means_b)
cooksd <- cooks.distance(model)
plot(cooksd, pch = 20, main = "Cook's D Plot", xlab = "Observation", ylab = "Cook's D")
mtext("BeReal", side = 3, line = 3, cex = 1.2)

means_i <- data.frame(M = rowMeans(data_i))
model <- lm(M ~ 1, data = means_i)
cooksd <- cooks.distance(model)
plot(cooksd, pch = 20, main = "Cook's D Plot", xlab = "Observation", ylab = "Cook's D")
mtext("Instagram", side = 3, line = 3, cex = 1.2)

means_s <- data.frame(M = rowMeans(data_s))
model <- lm(M ~ 1, data = means_s)
cooksd <- cooks.distance(model)
plot(cooksd, pch = 20, main = "Cook's D Plot", xlab = "Observation", ylab = "Cook's D")
mtext("ASMC", side = 3, line = 3, cex = 1.2)





# Scatterplot BeReal vs. Instagram mit linearer Regression
plot(data_b$M, data_i$M, 
     main = "Scatter Plot", 
     xlab = "BeReal", 
     ylab = "Instagram")
mtext("BeReal und Instagram", side = 3, line = 3, cex = 1.2)

# Lineare Regression
lm_model <- lm(data_i$M ~ data_b$M)
abline(lm_model, col = "black")

# Scatterplot BeReal vs. ASMC mit linearer Regression
plot(data_b$M, data_s$M, 
     main = "Scatter Plot", 
     xlab = "BeReal", 
     ylab = "ASMC")
mtext("BeReal und ASMC", side = 3, line = 3, cex = 1.2)

# Lineare Regression
lm_model <- lm(data_s$M ~ data_b$M)
abline(lm_model, col = "black")

# Scatterplot Instagram vs. ASMC mit linearer Regression
plot(data_i$M, data_s$M, 
     main = "Scatter Plot", 
     xlab = "Instagram", 
     ylab = "ASMC")
mtext("Instagram und ASMC", side = 3, line = 3, cex = 1.2)

# Lineare Regression
lm_model <- lm(data_s$M ~ data_i$M)
abline(lm_model, col = "black")

```
```{r}
library(ggplot2)
merged_data <- data.frame(data_b$M, data_i$M, data_s$M)
colnames(merged_data) <- c("b", "i", "s")
merged_data$bi <- (merged_data$b + merged_data$i) / 2
merged_data$Geschlecht <- data$Of2

#b und i
plot_data <- ggplot(merged_data, aes(x = b, y = i)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE, fullrange = TRUE, expand = c(0, 0)) +
  scale_x_continuous(limits = c(1, 7), breaks = 1:7) +
  scale_y_continuous(limits = c(1, 7), breaks = 1:7) +
  labs(x = "BeReal", y = "Instagram", title = "Scatterplot", 
       subtitle = "Relationship between Neu and Attitude",
       caption = "Data source: ueq") +
  theme_minimal()
plot_data

#b und s
plot_data <- ggplot(merged_data, aes(x = b, y = s)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE, fullrange = TRUE, expand = c(0, 0)) +
  scale_x_continuous(limits = c(1, 7), breaks = 1:7) +
  scale_y_continuous(limits = c(1, 7), breaks = 1:7) +
  labs(x = "BeReal", y = "Social Media", title = "Scatterplot", 
       subtitle = "Relationship between Neu and Attitude",
       caption = "Data source: ueq") +
  theme_minimal()
plot_data

#i und s
plot_data <- ggplot(merged_data, aes(x = i, y = s)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE, fullrange = TRUE, expand = c(0, 0)) +
  scale_x_continuous(limits = c(1, 7), breaks = 1:7) +
  scale_y_continuous(limits = c(1, 7), breaks = 1:7) +
  labs(x = "Instagram", y = "Social Media", title = "Scatterplot", 
       subtitle = "Relationship between Neu and Attitude",
       caption = "Data source: ueq") +
  theme_minimal()
plot_data

#b, i einzeln mit asmc
plot_data <- ggplot() +
  geom_point(data = merged_data, aes(x = b, y = s, color = "BeReal")) +
  geom_smooth(data = merged_data, aes(x = b, y = s, color = "BeReal"), method = "lm", se = FALSE, fullrange = TRUE, expand = c(0, 0)) +
  geom_point(data = merged_data, aes(x = i, y = s, color = "Instagram")) +
  geom_smooth(data = merged_data, aes(x = i, y = s, color = "Instagram"), method = "lm", se = FALSE, fullrange = TRUE, expand = c(0, 0)) +
  scale_x_continuous(limits = c(1, 7), breaks = 1:7) +
  scale_y_continuous(limits = c(1, 7), breaks = 1:7) +
  labs(x = "unsere Skala", y = "ASMC", title = "",
       subtitle = "",
       caption = "") +
  theme_minimal()
plot_data


#b, i zusammen mit asmc
plot_data <- ggplot(merged_data, aes(x = bi, y = s)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE, fullrange = TRUE, expand = c(0, 0)) +
  scale_x_continuous(limits = c(1, 7), breaks = 1:7) +
  scale_y_continuous(limits = c(1, 7), breaks = 1:7) +
  labs(x = "(BeReal + Instagram) / 2", y = "Social Media", title = "Scatterplot", 
       subtitle = "",
       caption = "") +
  theme_minimal()
plot_data



#alles
plot_data <- ggplot() +
  geom_point(data = merged_data, aes(x = b, y = s, color = "BeReal")) +
  geom_smooth(data = merged_data, aes(x = b, y = s, color = "BeReal"), method = "lm", se = FALSE, fullrange = TRUE, expand = c(0, 0)) +
  geom_point(data = merged_data, aes(x = i, y = s, color = "Instagram")) +
  geom_smooth(data = merged_data, aes(x = i, y = s, color = "Instagram"), method = "lm", se = FALSE, fullrange = TRUE, expand = c(0, 0)) +
  geom_point(data = merged_data, aes(x = bi, y = s, color = "Combined")) +
  geom_smooth(data = merged_data, aes(x = bi, y = s, color = "Combined"), method = "lm", se = FALSE, fullrange = TRUE, expand = c(0, 0)) +
  scale_x_continuous(limits = c(1, 7), breaks = 1:7) +
  scale_y_continuous(limits = c(1, 7), breaks = 1:7) +
  labs(x = "unsere Skala", y = "ASMC", title = "",
       subtitle = "",
       caption = "") +
  theme_minimal() +
  scale_color_manual(values = c("BeReal" = "red", "Instagram" = "blue", "Combined" = "green"))
plot_data

#m, w unterschieden mit b und s
plot_data <- ggplot(merged_data, aes(x = b, y = s, color = Geschlecht)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE, fullrange = TRUE, expand = c(0, 0)) +
  scale_x_continuous(limits = c(1, 7), breaks = 1:7) +
  scale_y_continuous(limits = c(1, 7), breaks = 1:7) +
  labs(x = "BeReal", y = "ASMC", title = "", 
       subtitle = "",
       caption = "") +
  theme_minimal()
plot_data

#m, w unterschieden mit i und s
plot_data <- ggplot(merged_data, aes(x = i, y = s, color = Geschlecht)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE, fullrange = TRUE, expand = c(0, 0)) +
  scale_x_continuous(limits = c(1, 7), breaks = 1:7) +
  scale_y_continuous(limits = c(1, 7), breaks = 1:7) +
  labs(x = "Instagram", y = "ASMC", title = "", 
       subtitle = "",
       caption = "") +
  theme_minimal()
plot_data




ggplot(merged_data, aes(x = "", y = b)) +
  geom_boxplot() +
  ylab("b") +
  xlab("") +
  theme_minimal()



ggplot(merged_data, aes(x = "", y = b)) +
       geom_boxplot()
```